import { archetypeIds } from "../../../core/archetypes/ids";
import type { ThemeCopy } from "../../../core/archetypes/contracts";

export const copy = {
  gameTitle: "Arena Survivor",
  arenaName: "The Ember Court",
  bootStatus: "The arena awaits",
  bootFailure: "The arena could not be summoned.",
  movementHint: "Move with WASD or arrow keys · Pause with Escape",
  levelUpTitle: "Choose a new blessing",
  vocabulary: {
    health: "Vitality",
    experience: "Arcane Power",
    level: "Rank",
    time: "Time",
    kills: "Foes Vanquished",
    enemies: "Foes Remaining",
    chaos: "Chaos",
    paused: "The arena is paused",
    deathTitle: "The Knight Has Fallen",
    deathMessage: "The Ember Court claims another challenger.",
    completeTitle: "The Trial Is Complete",
    completeMessage: "You endured the arena's full assault.",
    restartAction: "Begin Again",
    startAction: "Begin Run",
    startHint: "Press Enter or Space, or click to begin",
    shrinePrompt: "Press E or Space to invoke",
    shrineArrived: "A shrine has risen",
    surgeActive: "The horde answers",
    statisticsTitle: "Trial Record",
    peakEnemiesAlive: "Peak Foes",
    highestChaos: "Highest Chaos",
    highestCrit: "Highest Critical Chance",
    highestCritTier: "Highest Overcrit Tier",
    longestPierce: "Longest Pierce",
    largestKillChain: "Largest Kill Chain",
    totalDamage: "Total Damage",
    damageBreakdown: "Damage Ledger",
    directDamage: "Direct",
    criticalBonusDamage: "Critical Bonus",
    piercingMomentumDamage: "Piercing Momentum",
    explosionDamage: "Explosion",
    chainedExplosionDamage: "Chained Explosion",
    remainderDamage: "Other / Remainder",
    deathCause: "Slain by",
    timeUpTitle: "The Hour Is Up",
    timeUpMessage: "The appointed hour has passed, but the arena has not emptied. Decide how this one ends.",
    timeUpHint: "Press 1 or 2, or click",
    continueEndless: "Fight On",
    continueEndlessHint: "No end time. The horde keeps coming until you fall.",
    clearTheField: "Clear The Arena",
    clearTheFieldHint: "No new monsters. Finish what remains · still standing",
    upgradesTaken: "Blessings Taken",
  },
  stats: {
    health: "Vitality",
    damage: "Damage",
    attackRate: "Attack rate",
    critChance: "Critical chance",
    critDamage: "Critical damage",
    projectiles: "Projectiles",
    pierce: "Pierce",
    range: "Range",
    knockback: "Knockback",
    armourPierce: "Armour pierce",
    moveSpeed: "Move speed",
    pickupRadius: "Arcane reach",
    armour: "Armour",
    regeneration: "Regeneration",
    luck: "Luck",
    xpMultiplier: "Power bonus",
  },
  world: {
    chaos: "Chaos",
    enemySpawn: "Foes arriving",
    enemyHealth: "Foe durability",
    enemyDamage: "Foe harm",
    xpGain: "Power gain",
    eliteChance: "Elite chance",
    threat: "Threat level",
  },
  codex: {
    title: "Grimoire",
    shrines: "Shrines",
    reward: "Bounty",
    released: "Horde released",
    duplicates: "Duplicates",
    duplicatesValue: "Every monster present",
    upgrades: "Relics",
    session: "Session",
    sessionTotal: "This session",
    bestInRun: "Best run",
    maxPerRun: "Per run",
    runsPlayed: "Runs played",
    best: "Best",
  },
  tiers: {
    common: "Common",
    uncommon: "Uncommon",
    rare: "Rare",
    epic: "Epic",
    legendary: "Legendary",
    unique: "Unique",
  },
  content: {
    [archetypeIds.character.starter]: {
      name: "Wandering Knight",
      description: "A lone champion entering the Ember Court.",
    },
    [archetypeIds.weapon.starterProjectile]: {
      name: "Magic Needle",
      description: "A precise enchanted projectile that seeks the nearest foe.",
    },
    [archetypeIds.enemy.swarmBasic]: {
      name: "Grunt",
      description: "A frail creature dangerous in great numbers.",
    },
    [archetypeIds.enemy.fastFragile]: {
      name: "Runner",
      description: "A swift, fragile hunter that forces constant movement.",
    },
    [archetypeIds.enemy.slowDurable]: {
      name: "Tank",
      description: "A slow, durable obstacle that anchors the horde.",
    },
    [archetypeIds.enemy.deathSpawner]: {
      name: "Broodmother",
      description: "A swollen creature whose defeat releases a fresh brood.",
    },
    [archetypeIds.pickup.experience]: {
      name: "Arcane Spark",
      description: "A trace of power left by a fallen enemy.",
    },
    [archetypeIds.shrine.spawnSurge]: {
      name: "Shrine of the Horde",
      description: "Invite a dangerous swarm in exchange for greater rewards.",
    },
    [archetypeIds.shrine.greed]: { name: "Shrine of Greed", description: "Trade lasting danger for greater power." },
    [archetypeIds.shrine.multiplicity]: { name: "Shrine of Multiplicity", description: "Multiply both the horde and its rewards." },
    [archetypeIds.shrine.duplication]: { name: "Shrine of Duplication", description: "Copy every living foe for richer rewards." },
    [archetypeIds.skill.piercingMomentum]: { name: "Piercing Momentum", description: "A projectile gains force with every unique foe pierced." },
    [archetypeIds.skill.onKillExplosion]: { name: "Detonation", description: "Defeated foes damage nearby enemies." },
    [archetypeIds.skill.fracture]: { name: "Fracture", description: "Some defeated foes split into smaller enemies." },
    [archetypeIds.skill.bloodlust]: { name: "Bloodlust", description: "Recent kills quicken your attacks." },
    [archetypeIds.skill.chainReaction]: { name: "Chain Reaction", description: "Explosion kills may detonate in turn." },
    [archetypeIds.hazard.damageZone]: {
      name: "Cursed Mire",
      description: "A lingering blight that burns and drags at anything wading through it.",
    },
    [archetypeIds.hazard.obstacle]: {
      name: "Rubble Barricade",
      description: "Fallen stone that blocks movement and shots until it is cleared.",
    },
    [archetypeIds.hazard.periodicBurst]: {
      name: "Ember Geyser",
      description: "A vent that erupts on a cycle. The warning is the only warning.",
    },
    [archetypeIds.upgrade.damage]: {
      name: "Tempered Power",
      description: "Increase damage dealt.",
    },
    [archetypeIds.upgrade.attackSpeed]: {
      name: "Quickened Weave",
      description: "Attack more frequently.",
    },
    [archetypeIds.upgrade.critChance]: {
      name: "Critical Mass",
      description: "Increase critical strike chance.",
    },
    [archetypeIds.upgrade.pierce]: {
      name: "Sharpened Tip",
      description: "Projectiles pass through another enemy.",
    },
    [archetypeIds.upgrade.projectileCount]: {
      name: "Twin Casting",
      description: "Launch one additional projectile with every attack.",
    },
    [archetypeIds.upgrade.moveSpeed]: {
      name: "Fleet-Footed",
      description: "Move more quickly through the arena.",
    },
    [archetypeIds.upgrade.health]: {
      name: "Knight's Vigor",
      description: "Increase maximum health and heal by the same amount.",
    },
    [archetypeIds.upgrade.pickupRadius]: {
      name: "Arcane Reach",
      description: "Draw experience sparks from farther away.",
    },
    [archetypeIds.upgrade.piercingMomentum]: { name: "Piercing Momentum", description: "Each unique foe pierced adds 10% of the projectile's base damage." },
    [archetypeIds.upgrade.onKillExplosion]: { name: "Detonation", description: "Defeated foes erupt and damage nearby enemies." },
    [archetypeIds.upgrade.fracture]: { name: "Fracture", description: "Some defeated foes split into two fragile enemies." },
    [archetypeIds.upgrade.bloodlust]: { name: "Bloodlust", description: "Recent kills increase attack speed." },
    [archetypeIds.upgrade.chainReaction]: { name: "Chain Reaction", description: "Explosion kills can create further explosions." },
    [archetypeIds.upgrade.worldSurge]: {
      name: "Swarming",
      description: "Far more foes arrive, and defeating them is worth far more.",
    },
    [archetypeIds.upgrade.worldBrittle]: {
      name: "Glass World",
      description: "Double your power, and let the arena turn far deadlier.",
    },
    [archetypeIds.upgrade.armour]: {
      name: "Plated Guard",
      description: "Reduce the harm foes do on contact.",
    },
    [archetypeIds.upgrade.regeneration]: {
      name: "Renewing Vow",
      description: "Recover health steadily through the trial.",
    },
    [archetypeIds.upgrade.luck]: {
      name: "Fortune's Favour",
      description: "Rarer blessings turn up more often.",
    },
  },
} as const satisfies ThemeCopy;
