import { archetypeIds } from "../../../core/archetypes/ids";
import type { EnemyDefinition } from "../../../core/archetypes/contracts";

export const enemies = [
  {
    id: archetypeIds.enemy.swarmBasic,
    maxHealth: 20,
    moveSpeed: 70,
    contactDamage: 10,
    contactCooldownMs: 1000,
    radius: 14,
    xpReward: 1,
    spawnWeight: 56,
    unlockAtMs: 0,
    geometry: "circle",
    presentationToken: "enemy",
  },
  {
    id: archetypeIds.enemy.fastFragile,
    maxHealth: 10,
    moveSpeed: 140,
    contactDamage: 8,
    contactCooldownMs: 1000,
    radius: 10,
    xpReward: 1,
    spawnWeight: 24,
    unlockAtMs: 8_000,
    geometry: "triangle",
    presentationToken: "enemyFast",
  },
  {
    id: archetypeIds.enemy.slowDurable,
    maxHealth: 80,
    moveSpeed: 45,
    contactDamage: 20,
    contactCooldownMs: 1000,
    radius: 22,
    xpReward: 4,
    spawnWeight: 14,
    unlockAtMs: 16_000,
    geometry: "square",
    presentationToken: "enemyTank",
  },
  {
    id: archetypeIds.enemy.deathSpawner,
    maxHealth: 50,
    moveSpeed: 55,
    contactDamage: 12,
    contactCooldownMs: 1000,
    radius: 25,
    xpReward: 3,
    spawnWeight: 6,
    unlockAtMs: 24_000,
    geometry: "hexagon",
    presentationToken: "enemySpawner",
    deathSpawn: {
      enemyId: archetypeIds.enemy.fastFragile,
      count: 5,
      rewardMultiplier: 0,
    },
  },
] as const satisfies readonly EnemyDefinition[];
