import type { ThemeTokens } from "../../../core/archetypes/contracts";

export const tokens = {
  palette: {
    background: "#0a0f1b",
    floor: "#17213a",
    grid: "#263758",
    accent: "#d6ad55",
    text: "#f7e7b5",
    player: "#7dd3fc",
    enemy: "#e87979",
    enemyFast: "#fb923c",
    enemyTank: "#a78bfa",
    enemySpawner: "#f472b6",
    projectile: "#c4b5fd",
    critical: "#fbbf24",
    overcritical: "#ffffff",
    pickup: "#6ee7b7",
    health: "#ef4444",
    shrine: "#fb7185",
    explosion: "#f97316",
    elite: "#fde047",
  },
  tiers: {
    common: "#e2e8f0",
    uncommon: "#4ade80",
    rare: "#60a5fa",
    epic: "#c084fc",
    legendary: "#fbbf24",
    unique: "#fb7185",
  },
  playerShape: "diamond",
  feedback: {
    damage: "feedback.damage",
    critical: "feedback.critical",
    overcritical: "feedback.overcritical",
    pierce: "feedback.pierce",
    explosion: "feedback.explosion",
    shrine: "feedback.shrine",
    elite: "feedback.elite",
  },
  sounds: {
    damage: { frequency: 180, durationMs: 35, gain: 0.025 },
    critical: { frequency: 440, durationMs: 55, gain: 0.035 },
    overcritical: { frequency: 760, durationMs: 85, gain: 0.045 },
    pierce: { frequency: 520, durationMs: 45, gain: 0.025 },
    explosion: { frequency: 110, durationMs: 100, gain: 0.05 },
    shrine: { frequency: 330, durationMs: 140, gain: 0.05 },
    elite: { frequency: 220, durationMs: 180, gain: 0.045 },
  },
} as const satisfies ThemeTokens;
